version: '3'
services:
  # Creates an InfluxDB instance to store the
  influxdb:
    image: influxdb:latest
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminadmin
      - INFLUXDB_DB=szopipi
      
  # Displays the results in a Grafana dashborad
  grafana:
    image: grafana/grafana-oss:latest
    restart: always
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      
volumes:
  grafana:
  influxdb: